### ISSUE TITLE
fatal error when koop service is used as input for any analysis tool in the Map Viewer

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-output-geoservices#5]
> Accessing url https://adapters.koopernetes.com/zillow/atlanta/FeatureServer/0 returned error Proxy or Gateway Server did not allow the URL. Check with your LAN administrator that Proxy or Gateway server is configured to allow the URL. (status code 502).. Create Buffers failed. 

> Failed to access url https://adapters.koopernetes.com/zillow/atlanta/FeatureServer/0.

STR:

1. open http://www.arcgis.com/home/webmap/viewer.html?webmap=a3b82def31334e14ae799d025a6aff8e
2. attempt to create buffers, drive-times or enrich either of the two operational layers below.

tested with
* https://adapters.koopernetes.com/zillow/atlanta/FeatureServer/0
* https://h8w2a8ip0c.execute-api.us-east-1.amazonaws.com/latest/walmart/FeatureServer/0

this _used to_ work. its difficult to determine whats failing because you can't snoop the requests to the koop layers that the analysis service itself spawns.

**Comment by rgwozdz** [comment]
I've tracked this down to Winnow, https://github.com/koopjs/winnow/blob/master/src/options/normalizeOptions.js#L76-L91.  The `inSR` is arriving as a `Object` with properties `latestWkid` adn `wkid`, rather than the expected string. As a result, this function returns `"EPSG:[object Object]"`.  Working on a patch.
